### ISSUE TITLE
Remove breaks attribute for Day

### ISSUE THREAD

**Issue by James-iwell** [doctor-budoka/punch-card#49]
It's the same information that's found in timeblocks but it  can make `punch edit` more difficult since you have to edit the break indices twice.

**Comment by doctor-budoka** [comment]
This isn't technically true: Since the task name for a break could be anything, we can't really know what it will be. We'd need to enforce a specific name for breaks to do this, removing the ability to give a break a name (like "dinner" or "school-run"). 

The real issue here is that using `punch edit` to insert a break/update a current task to be a break is difficult (rather than the breaks attribute itself), so this would probably be best fixed another way. For instance, the `insert-task` command (#39 ) with the additional capability to insert breaks, or by updating `update-task` to handle breaks.

Closing this and opening an issue to have `update-task` handle breaks (#51 )
